# Generated by conch for bash.

if [[ $- == *i* ]]; then

    # block: base
    export PATH="$HOME/.local/bin":"$PATH"
fi

# block: editor
export EDITOR="nvim"

if [[ $- == *i* ]]; then

    # block: nvim
    if command -v -- 'nvim' >/dev/null 2>&1; then
        alias vim='nvim'
    fi

    # block: bat
    if command -v -- 'bat' >/dev/null 2>&1; then
        alias cat='bat'
    fi
fi
