# Generated by conch for fish.

if status is-interactive

    # block: base
    fish_add_path --prepend "$HOME/.local/bin";
end

# block: editor
set -gx EDITOR "nvim";

if status is-interactive

    # block: nvim
    if command -q -- "nvim"
        alias vim="nvim";
        alias v="nvim";
    end

    # block: bat
    if command -q -- "bat"
        alias cat="bat";
    end
end
