# Generated by conch for fish.

if not set -q __CONCH_FISH_SOURCED
    set -g __CONCH_SOURCED 1
    set -g __CONCH_FISH_SOURCED 1

    if status is-interactive

        # block: base
        fish_add_path --prepend "$HOME/.local/bin";
    end

    # block: editor
    set -gx EDITOR "nvim";

    if status is-interactive

        # block: nvim
        if command -q -- "nvim"
            alias vim="nvim";
            alias v="nvim";
        end

        # block: bat
        if command -q -- "bat"
            alias cat="bat";
        end
    end
end
