# Generated by conch for bash.

if [[ -z "${__CONCH_BASH_SOURCED:-}" ]]; then
    __CONCH_SOURCED=1
    __CONCH_BASH_SOURCED=1

    if [[ $- == *i* ]]; then

        # block: base
        export PATH="$HOME/.local/bin":"$PATH"
    fi

    # block: editor
    export EDITOR="nvim"

    if [[ $- == *i* ]]; then

        # block: nvim
        if command -v -- 'nvim' >/dev/null 2>&1; then
            alias vim='nvim'
        fi

        # block: bat
        if command -v -- 'bat' >/dev/null 2>&1; then
            alias cat='bat'
        fi
    fi
fi
