use std::process::Command;

#[test]
fn binary_inits_fish_output() {
    let output = Command::new(env!("CARGO_BIN_EXE_conch"))
        .args([
            "init",
            "fish",
            "--config",
            "tests/fixtures/configs/simple-single.toml",
        ])
        .output()
        .expect("failed to run conch binary");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(stdout.contains("# Generated by conch for fish."));
    assert!(stdout.contains("# block: simple"));
}

#[test]
fn check_can_target_a_single_shell() {
    let output = Command::new(env!("CARGO_BIN_EXE_conch"))
        .args(["check", "fish", "--config", "examples/conch.toml"])
        .output()
        .expect("failed to run conch binary");

    assert!(output.status.success());
}

#[test]
fn binary_inits_yaml_output() {
    let output = Command::new(env!("CARGO_BIN_EXE_conch"))
        .args([
            "init",
            "fish",
            "--config",
            "tests/fixtures/configs/simple-single.yaml",
        ])
        .output()
        .expect("failed to run conch binary");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(stdout.contains("# Generated by conch for fish."));
    assert!(stdout.contains("# block: simple"));
}

#[test]
fn binary_inits_json_output() {
    let output = Command::new(env!("CARGO_BIN_EXE_conch"))
        .args([
            "init",
            "fish",
            "--config",
            "tests/fixtures/configs/simple-single.json",
        ])
        .output()
        .expect("failed to run conch binary");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(stdout.contains("# Generated by conch for fish."));
    assert!(stdout.contains("# block: simple"));
}

#[test]
fn explain_reports_resolution_shape() {
    let output = Command::new(env!("CARGO_BIN_EXE_conch"))
        .args([
            "explain",
            "fish",
            "--color",
            "never",
            "--config",
            "examples/conch.toml",
        ])
        .output()
        .expect("failed to run conch binary");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(stdout.contains("conch explain fish init"));
    assert!(stdout.contains("Block order"));
    assert!(stdout.contains("Blocks"));
    assert!(stdout.contains("Env bindings"));
    assert!(stdout.contains("Alias bindings"));
    assert!(stdout.contains("PATH timeline"));
    assert!(stdout.contains("convenience  guarded"));
    assert!(stdout.contains("contributes PATH prepend \"~/.local/bin\""));
    assert!(stdout.contains("editor  unguarded"));
    assert!(stdout.contains("contributes env EDITOR=\"nvim\""));
}

#[test]
fn build_emits_folded_shell_output() {
    let output = Command::new(env!("CARGO_BIN_EXE_conch"))
        .args([
            "build",
            "fish",
            "--config",
            "tests/fixtures/configs/build-fold.toml",
        ])
        .output()
        .expect("failed to run conch binary");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(stdout.contains("# Generated by conch for fish."));
    assert!(stdout.contains("if not set -q __CONCH_FISH_SOURCED"));
    assert!(stdout.contains("if status is-interactive"));
    assert!(stdout.contains("set -q HOME"));
    assert!(!stdout.contains("shell:fish"));
    assert!(!stdout.contains("test -e \"Cargo.toml\""));
    assert!(stdout.contains("\"starship\" \"init\" \"fish\" | source"));
}

#[test]
fn init_explain_matches_explain_subcommand() {
    let init = Command::new(env!("CARGO_BIN_EXE_conch"))
        .args([
            "init",
            "fish",
            "--explain",
            "--color",
            "never",
            "--config",
            "tests/fixtures/configs/build-fold.toml",
        ])
        .output()
        .expect("failed to run conch binary");
    let explain = Command::new(env!("CARGO_BIN_EXE_conch"))
        .args([
            "explain",
            "fish",
            "init",
            "--color",
            "never",
            "--config",
            "tests/fixtures/configs/build-fold.toml",
        ])
        .output()
        .expect("failed to run conch binary");

    assert!(init.status.success());
    assert!(explain.status.success());
    assert_eq!(init.stdout, explain.stdout);
}

#[test]
fn build_explain_supports_compat_subcommand() {
    let build = Command::new(env!("CARGO_BIN_EXE_conch"))
        .args([
            "build",
            "fish",
            "--explain",
            "--color",
            "never",
            "--config",
            "tests/fixtures/configs/build-fold.toml",
        ])
        .output()
        .expect("failed to run conch binary");
    let explain = Command::new(env!("CARGO_BIN_EXE_conch"))
        .args([
            "explain",
            "fish",
            "build",
            "--color",
            "never",
            "--config",
            "tests/fixtures/configs/build-fold.toml",
        ])
        .output()
        .expect("failed to run conch binary");

    assert!(build.status.success());
    assert!(explain.status.success());
    assert_eq!(build.stdout, explain.stdout);
}

#[test]
fn explain_build_reports_build_mode() {
    let output = Command::new(env!("CARGO_BIN_EXE_conch"))
        .args([
            "explain",
            "fish",
            "build",
            "--color",
            "never",
            "--config",
            "tests/fixtures/configs/build-fold.toml",
        ])
        .output()
        .expect("failed to run conch binary");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(stdout.contains("conch explain fish build"));
    assert!(stdout.contains("when        interactive"));
    assert!(stdout.contains("requires    env:HOME"));
    assert!(!stdout.contains("shell:fish"));
    assert!(!stdout.contains("file:Cargo.toml"));
}

#[test]
fn complete_prints_fish_script() {
    let output = Command::new(env!("CARGO_BIN_EXE_conch"))
        .args(["complete", "fish"])
        .output()
        .expect("failed to run conch binary");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(
        stdout.contains("__fish_conch_needs_command"),
        "expected fish completion helpers, got: {stdout:?}"
    );
}

#[test]
fn missing_config_is_reported() {
    let output = Command::new(env!("CARGO_BIN_EXE_conch"))
        .args(["check", "--config", "missing.toml"])
        .output()
        .expect("failed to run conch binary");

    assert!(!output.status.success());
    let stderr = String::from_utf8(output.stderr).unwrap();
    assert!(stderr.contains("config file not found"));
}

#[test]
fn build_respects_os_flag_for_folding() {
    let cfg = "tests/fixtures/configs/os-linux-block.toml";

    let freebsd = Command::new(env!("CARGO_BIN_EXE_conch"))
        .args(["build", "fish", "--config", cfg, "--os", "freebsd"])
        .output()
        .expect("failed to run conch binary");
    assert!(freebsd.status.success(), "{:?}", freebsd.stderr);
    let out = String::from_utf8(freebsd.stdout).unwrap();
    assert!(
        !out.contains("CONCH_LINUX_ONLY"),
        "expected linux-only block dropped: {out}"
    );

    let linux = Command::new(env!("CARGO_BIN_EXE_conch"))
        .args(["build", "fish", "--config", cfg, "--os", "linux"])
        .output()
        .expect("failed to run conch binary");
    assert!(linux.status.success(), "{:?}", linux.stderr);
    let out = String::from_utf8(linux.stdout).unwrap();
    assert!(
        out.contains("CONCH_LINUX_ONLY"),
        "expected linux block kept: {out}"
    );
}

#[test]
fn init_explain_matches_with_shared_os_flag() {
    let cfg = "tests/fixtures/configs/os-linux-block.toml";
    let args_init = [
        "init",
        "fish",
        "--explain",
        "--color",
        "never",
        "--config",
        cfg,
        "--os",
        "freebsd",
    ];
    let args_explain = [
        "explain", "fish", "init", "--color", "never", "--config", cfg, "--os", "freebsd",
    ];
    let init = Command::new(env!("CARGO_BIN_EXE_conch"))
        .args(args_init)
        .output()
        .expect("failed to run conch binary");
    let explain = Command::new(env!("CARGO_BIN_EXE_conch"))
        .args(args_explain)
        .output()
        .expect("failed to run conch binary");

    assert!(init.status.success(), "{:?}", init.stderr);
    assert!(explain.status.success(), "{:?}", explain.stderr);
    assert_eq!(init.stdout, explain.stdout);
}

#[test]
fn explain_check_rejects_host_folding_flags() {
    let output = Command::new(env!("CARGO_BIN_EXE_conch"))
        .args([
            "explain",
            "fish",
            "check",
            "--config",
            "tests/fixtures/configs/simple-single.toml",
            "--os",
            "linux",
            "--hostname",
            "demo-host",
        ])
        .output()
        .expect("failed to run conch binary");

    assert!(!output.status.success());
    let stderr = String::from_utf8(output.stderr).unwrap();
    assert!(
        stderr.contains("does not use `--os` or `--hostname`"),
        "{stderr}"
    );
}
