use std::process::Command;

#[test]
fn binary_inits_fish_output() {
    let output = Command::new(env!("CARGO_BIN_EXE_conch"))
        .args([
            "init",
            "fish",
            "--config",
            "tests/fixtures/configs/simple-single.toml",
        ])
        .output()
        .expect("failed to run conch binary");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(stdout.contains("# Generated by conch for fish."));
    assert!(stdout.contains("# block: simple"));
}

#[test]
fn check_can_target_a_single_shell() {
    let output = Command::new(env!("CARGO_BIN_EXE_conch"))
        .args(["check", "fish", "--config", "examples/conch.toml"])
        .output()
        .expect("failed to run conch binary");

    assert!(output.status.success());
}

#[test]
fn binary_inits_yaml_output() {
    let output = Command::new(env!("CARGO_BIN_EXE_conch"))
        .args([
            "init",
            "fish",
            "--config",
            "tests/fixtures/configs/simple-single.yaml",
        ])
        .output()
        .expect("failed to run conch binary");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(stdout.contains("# Generated by conch for fish."));
    assert!(stdout.contains("# block: simple"));
}

#[test]
fn binary_inits_json_output() {
    let output = Command::new(env!("CARGO_BIN_EXE_conch"))
        .args([
            "init",
            "fish",
            "--config",
            "tests/fixtures/configs/simple-single.json",
        ])
        .output()
        .expect("failed to run conch binary");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(stdout.contains("# Generated by conch for fish."));
    assert!(stdout.contains("# block: simple"));
}

#[test]
fn explain_reports_resolution_shape() {
    let output = Command::new(env!("CARGO_BIN_EXE_conch"))
        .args([
            "explain",
            "fish",
            "--color",
            "never",
            "--config",
            "examples/conch.toml",
        ])
        .output()
        .expect("failed to run conch binary");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(stdout.contains("conch explain fish"));
    assert!(stdout.contains("Block order"));
    assert!(stdout.contains("Blocks"));
    assert!(stdout.contains("Env bindings"));
    assert!(stdout.contains("Alias bindings"));
    assert!(stdout.contains("PATH timeline"));
    assert!(stdout.contains("convenience  guarded"));
    assert!(stdout.contains("contributes PATH prepend \"~/.local/bin\""));
    assert!(stdout.contains("editor  unguarded"));
    assert!(stdout.contains("contributes env EDITOR=\"nvim\""));
}

#[test]
fn complete_prints_fish_script() {
    let output = Command::new(env!("CARGO_BIN_EXE_conch"))
        .args(["complete", "fish"])
        .output()
        .expect("failed to run conch binary");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(
        stdout.contains("__fish_conch_needs_command"),
        "expected fish completion helpers, got: {stdout:?}"
    );
}

#[test]
fn missing_config_is_reported() {
    let output = Command::new(env!("CARGO_BIN_EXE_conch"))
        .args(["check", "--config", "missing.toml"])
        .output()
        .expect("failed to run conch binary");

    assert!(!output.status.success());
    let stderr = String::from_utf8(output.stderr).unwrap();
    assert!(stderr.contains("config file not found"));
}
