//! Bash provider.
//!
//! Notes:
//! - renders `when` / `requires` as Bash guard expressions
//! - path `move_front` / `move_back` are approximated in v1 as prepend/append
//! - approximation is documented directly in generated output comments

use crate::config::EnvValue;
use crate::ir::{Action, PathOp, ResolvedIr};
use crate::predicate::{Predicate, PredicateAtom};
use crate::provider::{
    build_hoist_runs, push_indented_verbatim, HoistRun, HoistedBlock, ShellProvider,
};

#[derive(Debug, Default, Copy, Clone)]
pub struct BashProvider;

impl ShellProvider for BashProvider {
    fn render(&self, ir: &ResolvedIr) -> String {
        self.render_init(ir, false)
    }
}

impl BashProvider {
    pub fn render_init(&self, ir: &ResolvedIr, guard_enabled: bool) -> String {
        let mut out = String::new();
        out.push_str("# Generated by conch for bash.\n");

        if guard_enabled {
            out.push_str("\nif [[ -z \"${__CONCH_BASH_SOURCED:-}\" ]]; then\n");
            out.push_str("    __CONCH_SOURCED=1\n");
            out.push_str("    __CONCH_BASH_SOURCED=1\n");
            for run in build_hoist_runs(&ir.blocks) {
                render_run(&mut out, &run, "    ");
            }
            out.push_str("fi\n");
        } else {
            for run in build_hoist_runs(&ir.blocks) {
                render_run(&mut out, &run, "");
            }
        }

        out
    }
}

fn render_run(out: &mut String, run: &HoistRun<'_>, prefix: &str) {
    let outer_guard = render_predicates(&run.hoistable);
    if let Some(condition) = &outer_guard {
        out.push_str(&format!("\n{prefix}if {condition}; then\n"));
        let nested_prefix = format!("{prefix}    ");
        for hoisted in &run.blocks {
            render_hoisted_block(out, hoisted, &nested_prefix);
        }
        out.push_str(&format!("{prefix}fi\n"));
    } else {
        for hoisted in &run.blocks {
            render_hoisted_block(out, hoisted, prefix);
        }
    }
}

fn render_hoisted_block(out: &mut String, hoisted: &HoistedBlock<'_>, prefix: &str) {
    let block = hoisted.block;
    out.push_str(&format!("\n{prefix}# block: {}\n", block.block_id));

    let guard = render_predicate_lists(&hoisted.residual_when, &hoisted.residual_requires);
    let indent = if guard.is_some() {
        format!("{prefix}    ")
    } else {
        prefix.to_string()
    };
    if let Some(condition) = &guard {
        out.push_str(&format!("{prefix}if {condition}; then\n"));
    }
    for action in &block.actions {
        render_action(out, action, &indent);
    }
    if guard.is_some() {
        out.push_str(&format!("{prefix}fi\n"));
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum GuardPart {
    Constant(bool),
    Expr(String),
}

fn render_predicate_lists(when: &[Predicate], requires: &[Predicate]) -> Option<String> {
    let mut predicates = Vec::with_capacity(when.len() + requires.len());
    predicates.extend_from_slice(when);
    predicates.extend_from_slice(requires);
    render_predicates(&predicates)
}

fn render_predicates(predicates: &[Predicate]) -> Option<String> {
    let mut expressions = Vec::new();

    for part in predicates.iter().map(render_predicate) {
        match part {
            GuardPart::Constant(true) => {}
            GuardPart::Constant(false) => return Some("false".into()),
            GuardPart::Expr(expr) => expressions.push(expr),
        }
    }

    if expressions.is_empty() {
        None
    } else {
        Some(expressions.join(" && "))
    }
}

fn render_predicate(predicate: &Predicate) -> GuardPart {
    match render_atom(&predicate.atom) {
        GuardPart::Constant(value) => {
            GuardPart::Constant(if predicate.negated { !value } else { value })
        }
        GuardPart::Expr(expr) => {
            if predicate.negated {
                GuardPart::Expr(format!("! ( {expr} )"))
            } else {
                GuardPart::Expr(expr)
            }
        }
    }
}

fn render_atom(atom: &PredicateAtom) -> GuardPart {
    match atom {
        PredicateAtom::Interactive => GuardPart::Expr("[[ $- == *i* ]]".into()),
        PredicateAtom::Login => GuardPart::Expr("shopt -q login_shell".into()),
        PredicateAtom::Shell(name) => GuardPart::Constant(name.eq_ignore_ascii_case("bash")),
        PredicateAtom::Command(name) => GuardPart::Expr(format!(
            "command -v -- {} >/dev/null 2>&1",
            bash_single_quote(name)
        )),
        PredicateAtom::EnvExists(name) => {
            GuardPart::Expr(format!("[[ -n \"${{{name}:-}}\" ]]", name = name))
        }
        PredicateAtom::EnvEquals { name, value } => GuardPart::Expr(format!(
            "[[ \"${{{name}:-}}\" == {value} ]]",
            name = name,
            value = bash_double_quote(value)
        )),
        PredicateAtom::File(path) => GuardPart::Expr(format!("[[ -e {} ]]", shell_path(path))),
        PredicateAtom::Dir(path) => GuardPart::Expr(format!("[[ -d {} ]]", shell_path(path))),
        PredicateAtom::Os(name) => GuardPart::Expr(format!(
            "[[ \"$(uname -s | tr '[:upper:]' '[:lower:]')\" == {} ]]",
            bash_double_quote(name)
        )),
        PredicateAtom::Hostname(name) => GuardPart::Expr(format!(
            "[[ \"$(hostname)\" == {} ]]",
            bash_double_quote(name)
        )),
    }
}

fn render_action(out: &mut String, action: &Action, prefix: &str) {
    match action {
        Action::SetEnv { key, value } => {
            out.push_str(prefix);
            out.push_str(&format!("export {}={}\n", key, bash_env_value(value)));
        }
        Action::SetAlias { name, value } => {
            out.push_str(prefix);
            out.push_str(&format!("alias {}={}\n", name, bash_single_quote(value)));
        }
        Action::Path(op) => match op {
            PathOp::Prepend(path) => {
                out.push_str(prefix);
                out.push_str(&format!("export PATH={}:\"$PATH\"\n", shell_path(path)));
            }
            PathOp::Append(path) => {
                out.push_str(prefix);
                out.push_str(&format!("export PATH=\"$PATH\":{}\n", shell_path(path)));
            }
            PathOp::MoveFront(path) => {
                out.push_str(prefix);
                out.push_str("# conch: move_front approximated as prepend in bash\n");
                out.push_str(prefix);
                out.push_str(&format!("export PATH={}:\"$PATH\"\n", shell_path(path)));
            }
            PathOp::MoveBack(path) => {
                out.push_str(prefix);
                out.push_str("# conch: move_back approximated as append in bash\n");
                out.push_str(prefix);
                out.push_str(&format!("export PATH=\"$PATH\":{}\n", shell_path(path)));
            }
        },
        Action::SourceLines { lines } => {
            for entry in lines {
                push_indented_verbatim(out, entry, prefix);
            }
        }
    }
}

fn bash_env_value(value: &EnvValue) -> String {
    match value {
        EnvValue::Raw(raw) => raw.clone(),
        _ => bash_double_quote(&value.as_string()),
    }
}

fn bash_single_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\"'\"'"))
}

fn bash_double_quote(value: &str) -> String {
    format!(
        "\"{}\"",
        value
            .replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('$', "\\$")
            .replace('`', "\\`")
            .replace('!', "\\!")
    )
}

fn shell_path(value: &str) -> String {
    let normalised = super::normalise_home(value);
    bash_path_quote(&normalised)
}

fn bash_path_quote(value: &str) -> String {
    format!(
        "\"{}\"",
        value
            .replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('`', "\\`")
            .replace('!', "\\!")
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::EnvValue;
    use crate::ir::{Action, Block, PathOp, ResolvedIr};
    use crate::predicate::{Predicate, PredicateAtom};

    #[test]
    fn renders_bash_ir_with_guards() {
        let ir = ResolvedIr {
            blocks: vec![Block {
                block_id: "nvim".into(),
                when: vec![Predicate {
                    negated: false,
                    atom: PredicateAtom::Interactive,
                }],
                requires: vec![Predicate {
                    negated: false,
                    atom: PredicateAtom::Command("nvim".into()),
                }],
                actions: vec![
                    Action::SetEnv {
                        key: "EDITOR".into(),
                        value: "nvim".into(),
                    },
                    Action::SetAlias {
                        name: "vim".into(),
                        value: "nvim".into(),
                    },
                    Action::Path(PathOp::Append("~/.local/bin".into())),
                ],
            }],
        };

        let text = BashProvider.render(&ir);
        assert!(text.contains("if [[ $- == *i* ]]; then\n\n    # block: nvim\n    if command -v -- 'nvim' >/dev/null 2>&1; then"));
        assert!(text.contains("export EDITOR=\"nvim\""));
        assert!(text.contains("alias vim='nvim'"));
        assert!(text.contains("export PATH=\"$PATH\":\"$HOME/.local/bin\""));
    }

    #[test]
    fn omits_redundant_true_shell_predicates() {
        let ir = ResolvedIr {
            blocks: vec![Block {
                block_id: "demo".into(),
                when: vec![Predicate {
                    negated: false,
                    atom: PredicateAtom::Shell("bash".into()),
                }],
                requires: vec![],
                actions: vec![Action::SetAlias {
                    name: "vim".into(),
                    value: "nvim".into(),
                }],
            }],
        };

        let text = BashProvider.render(&ir);
        assert!(!text.contains("if true"));
        assert!(text.contains("alias vim='nvim'"));
    }

    #[test]
    fn renders_shell_specific_init_guard_when_enabled() {
        let ir = ResolvedIr {
            blocks: vec![Block {
                block_id: "demo".into(),
                when: vec![],
                requires: vec![],
                actions: vec![Action::SetAlias {
                    name: "vim".into(),
                    value: "nvim".into(),
                }],
            }],
        };

        let text = BashProvider.render_init(&ir, true);
        assert!(text.contains("if [[ -z \"${__CONCH_BASH_SOURCED:-}\" ]]; then"));
        assert!(text.contains("__CONCH_SOURCED=1"));
        assert!(text.contains("__CONCH_BASH_SOURCED=1"));
        assert!(!text.contains("[[ -z \"${__CONCH_SOURCED:-}\" ]]"));
        assert!(text.contains("    # block: demo\n    alias vim='nvim'"));
    }

    #[test]
    fn normalises_bare_home_in_paths() {
        let ir = ResolvedIr {
            blocks: vec![Block {
                block_id: "home".into(),
                when: vec![],
                requires: vec![],
                actions: vec![Action::Path(PathOp::Prepend("~".into()))],
            }],
        };

        let text = BashProvider.render(&ir);
        assert!(text.contains("export PATH=\"$HOME\":\"$PATH\""));
    }

    #[test]
    fn documents_move_back_approximation() {
        let ir = ResolvedIr {
            blocks: vec![Block {
                block_id: "go".into(),
                when: vec![],
                requires: vec![],
                actions: vec![Action::Path(PathOp::MoveBack("~/go/bin".into()))],
            }],
        };

        let text = BashProvider.render(&ir);
        assert!(text.contains("move_back approximated as append in bash"));
    }

    #[test]
    fn escapes_dollar_in_literal_values() {
        let ir = ResolvedIr {
            blocks: vec![Block {
                block_id: "demo".into(),
                when: vec![],
                requires: vec![],
                actions: vec![Action::SetEnv {
                    key: "PROMPT".into(),
                    value: "$HOME".into(),
                }],
            }],
        };

        let text = BashProvider.render(&ir);
        assert!(text.contains("export PROMPT=\"\\$HOME\""));
    }

    #[test]
    fn quotes_non_string_env_scalars_for_bash() {
        let ir = ResolvedIr {
            blocks: vec![Block {
                block_id: "demo".into(),
                when: vec![],
                requires: vec![],
                actions: vec![
                    Action::SetEnv {
                        key: "ENABLED".into(),
                        value: EnvValue::Bool(true),
                    },
                    Action::SetEnv {
                        key: "RETRIES".into(),
                        value: EnvValue::Integer("1".into()),
                    },
                ],
            }],
        };

        let text = BashProvider.render(&ir);
        assert!(text.contains("export ENABLED=\"true\""));
        assert!(text.contains("export RETRIES=\"1\""));
    }

    #[test]
    fn emits_raw_env_values_without_quoting() {
        let ir = ResolvedIr {
            blocks: vec![Block {
                block_id: "demo".into(),
                when: vec![],
                requires: vec![],
                actions: vec![Action::SetEnv {
                    key: "LEAN_CTX_BIN".into(),
                    value: EnvValue::Raw("$(command -v lean-ctx)".into()),
                }],
            }],
        };

        let text = BashProvider.render(&ir);
        assert!(text.contains("export LEAN_CTX_BIN=$(command -v lean-ctx)"));
    }

    #[test]
    fn renders_source_lines_inside_guards() {
        let ir = ResolvedIr {
            blocks: vec![Block {
                block_id: "starship".into(),
                when: vec![Predicate {
                    negated: false,
                    atom: PredicateAtom::Interactive,
                }],
                requires: vec![Predicate {
                    negated: false,
                    atom: PredicateAtom::Command("starship".into()),
                }],
                actions: vec![Action::SourceLines {
                    lines: vec!["eval \"$(starship init bash)\"".into()],
                }],
            }],
        };

        let text = BashProvider.render(&ir);
        assert!(text.contains("if [[ $- == *i* ]]; then\n\n    # block: starship\n    if command -v -- 'starship' >/dev/null 2>&1; then"));
        assert!(text.contains("eval \"$(starship init bash)\""));
    }

    #[test]
    fn indents_every_source_line_inside_guards() {
        let ir = ResolvedIr {
            blocks: vec![Block {
                block_id: "demo".into(),
                when: vec![Predicate {
                    negated: false,
                    atom: PredicateAtom::Interactive,
                }],
                requires: vec![],
                actions: vec![Action::SourceLines {
                    lines: vec!["echo a".into(), "echo b".into()],
                }],
            }],
        };

        let text = BashProvider.render(&ir);
        let body = text
            .split_once("if [[ $- == *i* ]]; then\n")
            .unwrap()
            .1
            .split_once("fi\n")
            .unwrap()
            .0;
        assert_eq!(
            body, "\n    # block: demo\n    echo a\n    echo b\n",
            "each logical line must stay inside the guarded block"
        );
    }

    #[test]
    fn indents_move_front_comment_and_export_inside_guards() {
        let ir = ResolvedIr {
            blocks: vec![Block {
                block_id: "demo".into(),
                when: vec![Predicate {
                    negated: false,
                    atom: PredicateAtom::Interactive,
                }],
                requires: vec![],
                actions: vec![Action::Path(PathOp::MoveFront("~/bin".into()))],
            }],
        };

        let text = BashProvider.render(&ir);
        assert!(text
            .contains("    # conch: move_front approximated as prepend in bash\n    export PATH="));
    }

    #[test]
    fn indents_move_back_comment_and_export_inside_guards() {
        let ir = ResolvedIr {
            blocks: vec![Block {
                block_id: "demo".into(),
                when: vec![Predicate {
                    negated: false,
                    atom: PredicateAtom::Interactive,
                }],
                requires: vec![],
                actions: vec![Action::Path(PathOp::MoveBack("~/bin".into()))],
            }],
        };

        let text = BashProvider.render(&ir);
        assert!(text
            .contains("    # conch: move_back approximated as append in bash\n    export PATH="));
    }

    #[test]
    fn hoists_shared_interactive_guard_across_adjacent_blocks() {
        let ir = ResolvedIr {
            blocks: vec![
                Block {
                    block_id: "nvim".into(),
                    when: vec![Predicate {
                        negated: false,
                        atom: PredicateAtom::Interactive,
                    }],
                    requires: vec![Predicate {
                        negated: false,
                        atom: PredicateAtom::Command("nvim".into()),
                    }],
                    actions: vec![Action::SetAlias {
                        name: "vim".into(),
                        value: "nvim".into(),
                    }],
                },
                Block {
                    block_id: "bat".into(),
                    when: vec![Predicate {
                        negated: false,
                        atom: PredicateAtom::Interactive,
                    }],
                    requires: vec![Predicate {
                        negated: false,
                        atom: PredicateAtom::Command("bat".into()),
                    }],
                    actions: vec![Action::SetAlias {
                        name: "cat".into(),
                        value: "bat".into(),
                    }],
                },
            ],
        };

        let text = BashProvider.render(&ir);
        assert_eq!(text.matches("if [[ $- == *i* ]]; then").count(), 1);
        assert!(
            text.contains("    # block: nvim\n    if command -v -- 'nvim' >/dev/null 2>&1; then")
        );
        assert!(text.contains("    # block: bat\n    if command -v -- 'bat' >/dev/null 2>&1; then"));
    }

    #[test]
    fn hoists_shared_negated_interactive_guard() {
        let ir = ResolvedIr {
            blocks: vec![
                Block {
                    block_id: "non_interactive_a".into(),
                    when: vec![Predicate {
                        negated: true,
                        atom: PredicateAtom::Interactive,
                    }],
                    requires: vec![],
                    actions: vec![Action::SetEnv {
                        key: "A".into(),
                        value: "1".into(),
                    }],
                },
                Block {
                    block_id: "non_interactive_b".into(),
                    when: vec![Predicate {
                        negated: true,
                        atom: PredicateAtom::Interactive,
                    }],
                    requires: vec![],
                    actions: vec![Action::SetEnv {
                        key: "B".into(),
                        value: "1".into(),
                    }],
                },
            ],
        };

        let text = BashProvider.render(&ir);
        assert_eq!(text.matches("if ! ( [[ $- == *i* ]] ); then").count(), 1);
        assert!(text.contains("    # block: non_interactive_a\n    export A=\"1\""));
        assert!(text.contains("    # block: non_interactive_b\n    export B=\"1\""));
    }

    #[test]
    fn hoists_shared_interactive_and_login_guard_despite_order_difference() {
        let ir = ResolvedIr {
            blocks: vec![
                Block {
                    block_id: "a".into(),
                    when: vec![
                        Predicate {
                            negated: false,
                            atom: PredicateAtom::Interactive,
                        },
                        Predicate {
                            negated: false,
                            atom: PredicateAtom::Login,
                        },
                    ],
                    requires: vec![],
                    actions: vec![Action::SetEnv {
                        key: "A".into(),
                        value: "1".into(),
                    }],
                },
                Block {
                    block_id: "b".into(),
                    when: vec![Predicate {
                        negated: false,
                        atom: PredicateAtom::Login,
                    }],
                    requires: vec![Predicate {
                        negated: false,
                        atom: PredicateAtom::Interactive,
                    }],
                    actions: vec![Action::SetEnv {
                        key: "B".into(),
                        value: "1".into(),
                    }],
                },
            ],
        };

        let text = BashProvider.render(&ir);
        assert_eq!(
            text.matches("if [[ $- == *i* ]] && shopt -q login_shell; then")
                .count(),
            1
        );
        assert!(text.contains("    # block: a\n    export A=\"1\""));
        assert!(text.contains("    # block: b\n    export B=\"1\""));
    }

    #[test]
    fn does_not_hoist_different_hoistable_combinations() {
        let ir = ResolvedIr {
            blocks: vec![
                Block {
                    block_id: "interactive_only".into(),
                    when: vec![Predicate {
                        negated: false,
                        atom: PredicateAtom::Interactive,
                    }],
                    requires: vec![],
                    actions: vec![Action::SetEnv {
                        key: "A".into(),
                        value: "1".into(),
                    }],
                },
                Block {
                    block_id: "interactive_login".into(),
                    when: vec![
                        Predicate {
                            negated: false,
                            atom: PredicateAtom::Interactive,
                        },
                        Predicate {
                            negated: false,
                            atom: PredicateAtom::Login,
                        },
                    ],
                    requires: vec![],
                    actions: vec![Action::SetEnv {
                        key: "B".into(),
                        value: "1".into(),
                    }],
                },
            ],
        };

        let text = BashProvider.render(&ir);
        assert_eq!(text.matches("if [[ $- == *i* ]]; then").count(), 1);
        assert_eq!(
            text.matches("if [[ $- == *i* ]] && shopt -q login_shell; then")
                .count(),
            1
        );
    }

    #[test]
    fn renders_directory_predicates() {
        let ir = ResolvedIr {
            blocks: vec![Block {
                block_id: "cfg".into(),
                when: vec![],
                requires: vec![Predicate {
                    negated: false,
                    atom: PredicateAtom::Dir("~/.config/nvim".into()),
                }],
                actions: vec![Action::SetEnv {
                    key: "NVIM_CONFIGURED".into(),
                    value: "1".into(),
                }],
            }],
        };

        let text = BashProvider.render(&ir);
        assert!(text.contains("if [[ -d \"$HOME/.config/nvim\" ]]; then"));
        assert!(text.contains("export NVIM_CONFIGURED=\"1\""));
    }

    #[test]
    fn does_not_hoist_non_adjacent_blocks() {
        let ir = ResolvedIr {
            blocks: vec![
                Block {
                    block_id: "nvim".into(),
                    when: vec![Predicate {
                        negated: false,
                        atom: PredicateAtom::Interactive,
                    }],
                    requires: vec![],
                    actions: vec![Action::SetAlias {
                        name: "vim".into(),
                        value: "nvim".into(),
                    }],
                },
                Block {
                    block_id: "editor".into(),
                    when: vec![],
                    requires: vec![],
                    actions: vec![Action::SetEnv {
                        key: "EDITOR".into(),
                        value: "nvim".into(),
                    }],
                },
                Block {
                    block_id: "bat".into(),
                    when: vec![Predicate {
                        negated: false,
                        atom: PredicateAtom::Interactive,
                    }],
                    requires: vec![],
                    actions: vec![Action::SetAlias {
                        name: "cat".into(),
                        value: "bat".into(),
                    }],
                },
            ],
        };

        let text = BashProvider.render(&ir);
        assert_eq!(text.matches("if [[ $- == *i* ]]; then").count(), 2);
    }
}
