//! Fish provider.
//!
//! Notes:
//! - renders `when` / `requires` as Fish guard expressions
//! - uses `fish_add_path` for path mutations
//! - supports precise `move_front` / `move_back` via `fish_add_path --move`

use crate::config::{EnvValue, SourceEntry};
use crate::ir::{Action, PathOp, ResolvedIr};
use crate::predicate::{Predicate, PredicateAtom};
use crate::provider::{
    build_hoist_runs, push_indented_verbatim, source_command_for_shell, subst, HoistRun,
    HoistedBlock, ShellProvider,
};

#[derive(Debug, Default, Copy, Clone)]
pub struct FishProvider;

impl ShellProvider for FishProvider {
    fn render(&self, ir: &ResolvedIr) -> String {
        self.render_init(ir, false)
    }
}

impl FishProvider {
    pub fn render_init(&self, ir: &ResolvedIr, guard_enabled: bool) -> String {
        let mut out = String::new();
        out.push_str("# Generated by conch for fish.\n");

        if guard_enabled {
            out.push_str("\nif not set -q __CONCH_FISH_SOURCED\n");
            out.push_str("    set -g __CONCH_SOURCED 1\n");
            out.push_str("    set -g __CONCH_FISH_SOURCED 1\n");
            for run in build_hoist_runs(&ir.blocks) {
                render_run(&mut out, &run, "    ");
            }
            out.push_str("end\n");
        } else {
            for run in build_hoist_runs(&ir.blocks) {
                render_run(&mut out, &run, "");
            }
        }

        out
    }
}

fn render_run(out: &mut String, run: &HoistRun<'_>, prefix: &str) {
    let outer_guard = render_predicates(&run.hoistable);
    if let Some(condition) = &outer_guard {
        out.push_str(&format!("\n{prefix}if {condition}\n"));
        let nested_prefix = format!("{prefix}    ");
        for hoisted in &run.blocks {
            render_hoisted_block(out, hoisted, &nested_prefix);
        }
        out.push_str(&format!("{prefix}end\n"));
    } else {
        for hoisted in &run.blocks {
            render_hoisted_block(out, hoisted, prefix);
        }
    }
}

fn render_hoisted_block(out: &mut String, hoisted: &HoistedBlock<'_>, prefix: &str) {
    let block = hoisted.block;
    out.push_str(&format!("\n{prefix}# block: {}\n", block.block_id));

    let guard = render_predicate_lists(&hoisted.residual_when, &hoisted.residual_requires);
    let indent = if guard.is_some() {
        format!("{prefix}    ")
    } else {
        prefix.to_string()
    };
    if let Some(condition) = &guard {
        out.push_str(&format!("{prefix}if {condition}\n"));
    }
    for action in &block.actions {
        render_action(out, action, &indent);
    }
    if guard.is_some() {
        out.push_str(&format!("{prefix}end\n"));
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum GuardPart {
    Constant(bool),
    Expr(String),
}

fn render_predicate_lists(when: &[Predicate], requires: &[Predicate]) -> Option<String> {
    let mut predicates = Vec::with_capacity(when.len() + requires.len());
    predicates.extend_from_slice(when);
    predicates.extend_from_slice(requires);
    render_predicates(&predicates)
}

fn render_predicates(predicates: &[Predicate]) -> Option<String> {
    let mut expressions = Vec::new();

    for part in predicates.iter().map(render_predicate) {
        match part {
            GuardPart::Constant(true) => {}
            GuardPart::Constant(false) => return Some("false".into()),
            GuardPart::Expr(expr) => expressions.push(expr),
        }
    }

    match expressions.len() {
        0 => None,
        1 => expressions.into_iter().next(),
        _ => Some(format!("begin; {}; end", expressions.join("; and "))),
    }
}

fn render_predicate(predicate: &Predicate) -> GuardPart {
    match render_atom(&predicate.atom) {
        GuardPart::Constant(value) => {
            GuardPart::Constant(if predicate.negated { !value } else { value })
        }
        GuardPart::Expr(expr) => {
            if predicate.negated {
                GuardPart::Expr(format!("not {expr}"))
            } else {
                GuardPart::Expr(expr)
            }
        }
    }
}

fn render_atom(atom: &PredicateAtom) -> GuardPart {
    match atom {
        PredicateAtom::Interactive => GuardPart::Expr("status is-interactive".into()),
        PredicateAtom::Login => GuardPart::Expr("status is-login".into()),
        PredicateAtom::Shell(name) => GuardPart::Constant(name.eq_ignore_ascii_case("fish")),
        PredicateAtom::Command(name) => {
            GuardPart::Expr(format!("command -q -- {}", fish_string(name)))
        }
        PredicateAtom::EnvExists(name) => GuardPart::Expr(format!(
            "begin; set -q {name}; and test -n \"${name}\"; end",
            name = name
        )),
        PredicateAtom::EnvEquals { name, value } => GuardPart::Expr(format!(
            "begin; set -q {name}; and test \"${name}\" = {value}; end",
            name = name,
            value = fish_string(value)
        )),
        PredicateAtom::File(path) => GuardPart::Expr(format!("test -e {}", shell_path(path))),
        PredicateAtom::Dir(path) => GuardPart::Expr(format!("test -d {}", shell_path(path))),
        PredicateAtom::Os(name) => GuardPart::Expr(format!(
            "test (uname -s | string lower) = {}",
            fish_string(name)
        )),
        PredicateAtom::Hostname(name) => {
            GuardPart::Expr(format!("test (hostname) = {}", fish_string(name)))
        }
    }
}

fn render_action(out: &mut String, action: &Action, prefix: &str) {
    match action {
        Action::SetEnv { key, value } => {
            out.push_str(prefix);
            out.push_str(&format!("set -gx {} {};\n", key, fish_env_value(value)));
        }
        Action::SetAlias { name, value } => {
            out.push_str(prefix);
            out.push_str(&format!("alias {}={};\n", name, fish_string(value)));
        }
        Action::Path(op) => match op {
            PathOp::Prepend(path) => {
                out.push_str(prefix);
                out.push_str(&format!("fish_add_path --prepend {};\n", shell_path(path)));
            }
            PathOp::Append(path) => {
                out.push_str(prefix);
                out.push_str(&format!("fish_add_path --append {};\n", shell_path(path)));
            }
            PathOp::MoveFront(path) => {
                out.push_str(prefix);
                out.push_str(&format!(
                    "fish_add_path --move --prepend {};\n",
                    shell_path(path)
                ));
            }
            PathOp::MoveBack(path) => {
                out.push_str(prefix);
                out.push_str(&format!(
                    "fish_add_path --move --append {};\n",
                    shell_path(path)
                ));
            }
        },
        Action::Source(source) => match source {
            SourceEntry::File(path) => {
                out.push_str(prefix);
                out.push_str(&format!("source {}\n", shell_path(path)));
            }
            SourceEntry::Command(command) => {
                let rendered = render_source_command(command);
                out.push_str(prefix);
                out.push_str(&format!("{rendered} | source\n"));
            }
        },
        Action::SourceLines { lines } => {
            for entry in lines {
                push_indented_verbatim(out, entry, prefix);
            }
        }
    }
}

fn render_source_command(command: &[String]) -> String {
    source_command_for_shell(command, "fish")
        .iter()
        .map(|part| fish_command_arg(part))
        .collect::<Vec<_>>()
        .join(" ")
}

fn fish_command_arg(value: &str) -> String {
    let segs = subst::parse_interpolated_value(value)
        .expect("interpolated command arguments must have been validated when loading config");
    if segs.len() == 1 {
        if let subst::InterpSegment::Lit(s) = &segs[0] {
            return fish_string(s);
        }
    }
    subst::fish_render_interpolated(&segs)
}

fn fish_env_value(value: &EnvValue) -> String {
    match value {
        EnvValue::String(value) => {
            let segs = subst::parse_interpolated_value(value)
                .expect("interpolated env values must have been validated when loading config");
            subst::fish_render_interpolated(&segs)
        }
        EnvValue::Bool(value) => value.to_string(),
        EnvValue::Integer(value) => value.clone(),
        EnvValue::Raw(value) => value.clone(),
    }
}

fn fish_string(value: &str) -> String {
    let escaped = value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('$', "\\$")
        .replace('(', "\\(")
        .replace(')', "\\)");
    format!("\"{escaped}\"")
}

fn shell_path(value: &str) -> String {
    let segs = subst::parse_interpolated_value(value)
        .expect("interpolated paths must have been validated when loading config");
    subst::fish_render_path_interpolated(&segs)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{EnvValue, SourceEntry};
    use crate::ir::{Action, Block, PathOp, ResolvedIr};
    use crate::predicate::{Predicate, PredicateAtom};

    #[test]
    fn renders_fish_ir_with_guards() {
        let ir = ResolvedIr {
            blocks: vec![Block {
                block_id: "nvim".into(),
                when: vec![Predicate {
                    negated: false,
                    atom: PredicateAtom::Interactive,
                }],
                requires: vec![Predicate {
                    negated: false,
                    atom: PredicateAtom::Command("nvim".into()),
                }],
                actions: vec![
                    Action::SetEnv {
                        key: "EDITOR".into(),
                        value: "nvim".into(),
                    },
                    Action::SetAlias {
                        name: "vim".into(),
                        value: "nvim".into(),
                    },
                    Action::Path(PathOp::Prepend("~/.local/bin".into())),
                ],
            }],
        };

        let text = FishProvider.render(&ir);
        assert!(text.contains(
            "if status is-interactive\n\n    # block: nvim\n    if command -q -- \"nvim\"",
        ));
        assert!(text.contains("set -gx EDITOR \"nvim\";"));
        assert!(text.contains("alias vim=\"nvim\";"));
        assert!(text.contains("fish_add_path --prepend \"$HOME/.local/bin\";"));
    }

    #[test]
    fn omits_redundant_true_shell_predicates() {
        let ir = ResolvedIr {
            blocks: vec![Block {
                block_id: "demo".into(),
                when: vec![Predicate {
                    negated: false,
                    atom: PredicateAtom::Shell("fish".into()),
                }],
                requires: vec![],
                actions: vec![Action::SetAlias {
                    name: "vim".into(),
                    value: "nvim".into(),
                }],
            }],
        };

        let text = FishProvider.render(&ir);
        assert!(!text.contains("if true"));
        assert!(text.contains("alias vim=\"nvim\";"));
    }

    #[test]
    fn renders_shell_specific_init_guard_when_enabled() {
        let ir = ResolvedIr {
            blocks: vec![Block {
                block_id: "demo".into(),
                when: vec![],
                requires: vec![],
                actions: vec![Action::SetAlias {
                    name: "vim".into(),
                    value: "nvim".into(),
                }],
            }],
        };

        let text = FishProvider.render_init(&ir, true);
        assert!(text.contains("if not set -q __CONCH_FISH_SOURCED"));
        assert!(text.contains("set -g __CONCH_SOURCED 1"));
        assert!(text.contains("set -g __CONCH_FISH_SOURCED 1"));
        assert!(!text.contains("if not set -q __CONCH_SOURCED"));
        assert!(text.contains("    # block: demo\n    alias vim=\"nvim\";"));
    }

    #[test]
    fn normalises_bare_home_in_paths() {
        let ir = ResolvedIr {
            blocks: vec![Block {
                block_id: "home".into(),
                when: vec![],
                requires: vec![],
                actions: vec![Action::Path(PathOp::Prepend("~".into()))],
            }],
        };

        let text = FishProvider.render(&ir);
        assert!(text.contains("fish_add_path --prepend \"$HOME\";"));
    }

    #[test]
    fn quotes_env_equals_predicates_as_literals() {
        let ir = ResolvedIr {
            blocks: vec![Block {
                block_id: "demo".into(),
                when: vec![Predicate {
                    negated: false,
                    atom: PredicateAtom::EnvEquals {
                        name: "EDITOR".into(),
                        value: "~/bin/(nvim)".into(),
                    },
                }],
                requires: vec![],
                actions: vec![Action::SetAlias {
                    name: "vim".into(),
                    value: "nvim".into(),
                }],
            }],
        };

        let text = FishProvider.render(&ir);
        assert!(text.contains("test \"$EDITOR\" = \"~/bin/\\(nvim\\)\""));
    }

    #[test]
    fn renders_structured_source_actions_inside_guards() {
        let ir = ResolvedIr {
            blocks: vec![Block {
                block_id: "starship".into(),
                when: vec![Predicate {
                    negated: false,
                    atom: PredicateAtom::Interactive,
                }],
                requires: vec![Predicate {
                    negated: false,
                    atom: PredicateAtom::Command("starship".into()),
                }],
                actions: vec![
                    Action::Source(SourceEntry::File("~/.config/fish/local.fish".into())),
                    Action::Source(SourceEntry::Command(vec![
                        "starship".into(),
                        "init".into(),
                        "{shell}".into(),
                    ])),
                    Action::Source(SourceEntry::Command(vec![
                        "tool".into(),
                        "--config".into(),
                        "~/.config/tool/config.toml".into(),
                    ])),
                    Action::SourceLines {
                        lines: vec!["starship init fish | source".into()],
                    },
                ],
            }],
        };

        let text = FishProvider.render(&ir);
        assert!(text.contains(
            "if status is-interactive\n\n    # block: starship\n    if command -q -- \"starship\"",
        ));
        assert!(text.contains("source \"$HOME/.config/fish/local.fish\""));
        assert!(text.contains("\"starship\" \"init\" \"fish\" | source"));
        assert!(text.contains("\"tool\" \"--config\" \"$HOME/.config/tool/config.toml\" | source"));
        assert!(text.contains("starship init fish | source"));
    }

    #[test]
    fn renders_native_fish_scalars_for_env_values() {
        let ir = ResolvedIr {
            blocks: vec![Block {
                block_id: "demo".into(),
                when: vec![],
                requires: vec![],
                actions: vec![
                    Action::SetEnv {
                        key: "ENABLED".into(),
                        value: EnvValue::Bool(true),
                    },
                    Action::SetEnv {
                        key: "RETRIES".into(),
                        value: EnvValue::Integer("1".into()),
                    },
                    Action::SetEnv {
                        key: "EDITOR".into(),
                        value: EnvValue::String("nvim".into()),
                    },
                    Action::SetEnv {
                        key: "LEAN_CTX_BIN".into(),
                        value: EnvValue::Raw("(command -v lean-ctx)".into()),
                    },
                ],
            }],
        };

        let text = FishProvider.render(&ir);
        assert!(text.contains("set -gx ENABLED true;"));
        assert!(text.contains("set -gx RETRIES 1;"));
        assert!(text.contains("set -gx EDITOR \"nvim\";"));
        assert!(text.contains("set -gx LEAN_CTX_BIN (command -v lean-ctx);"));
    }

    #[test]
    fn interpolates_env_dollar_brace_and_tilde_in_string_env() {
        let ir = ResolvedIr {
            blocks: vec![Block {
                block_id: "demo".into(),
                when: vec![],
                requires: vec![],
                actions: vec![
                    Action::SetEnv {
                        key: "XDG_BIN_HOME".into(),
                        value: "${env:HOME}/.local/bin".into(),
                    },
                    Action::SetEnv {
                        key: "LOCAL".into(),
                        value: "~/.local".into(),
                    },
                ],
            }],
        };

        let text = FishProvider.render(&ir);
        assert!(text.contains("set -gx XDG_BIN_HOME \"$HOME/.local/bin\";"));
        assert!(text.contains("set -gx LOCAL \"$HOME/.local\";"));
    }

    #[test]
    fn indents_every_source_line_inside_guards() {
        let ir = ResolvedIr {
            blocks: vec![Block {
                block_id: "demo".into(),
                when: vec![Predicate {
                    negated: false,
                    atom: PredicateAtom::Interactive,
                }],
                requires: vec![],
                actions: vec![Action::SourceLines {
                    lines: vec!["echo a".into(), "echo b".into()],
                }],
            }],
        };

        let text = FishProvider.render(&ir);
        let body = text
            .split_once("if status is-interactive\n")
            .unwrap()
            .1
            .split_once("end\n")
            .unwrap()
            .0;
        assert_eq!(
            body, "\n    # block: demo\n    echo a\n    echo b\n",
            "each logical line must stay inside the guarded block"
        );
    }

    #[test]
    fn hoists_shared_interactive_guard_across_adjacent_blocks() {
        let ir = ResolvedIr {
            blocks: vec![
                Block {
                    block_id: "nvim".into(),
                    when: vec![Predicate {
                        negated: false,
                        atom: PredicateAtom::Interactive,
                    }],
                    requires: vec![Predicate {
                        negated: false,
                        atom: PredicateAtom::Command("nvim".into()),
                    }],
                    actions: vec![Action::SetAlias {
                        name: "vim".into(),
                        value: "nvim".into(),
                    }],
                },
                Block {
                    block_id: "bat".into(),
                    when: vec![Predicate {
                        negated: false,
                        atom: PredicateAtom::Interactive,
                    }],
                    requires: vec![Predicate {
                        negated: false,
                        atom: PredicateAtom::Command("bat".into()),
                    }],
                    actions: vec![Action::SetAlias {
                        name: "cat".into(),
                        value: "bat".into(),
                    }],
                },
            ],
        };

        let text = FishProvider.render(&ir);
        assert_eq!(text.matches("if status is-interactive").count(), 1);
        assert!(text.contains("    # block: nvim\n    if command -q -- \"nvim\""));
        assert!(text.contains("    # block: bat\n    if command -q -- \"bat\""));
    }

    #[test]
    fn hoists_shared_negated_interactive_guard() {
        let ir = ResolvedIr {
            blocks: vec![
                Block {
                    block_id: "non_interactive_a".into(),
                    when: vec![Predicate {
                        negated: true,
                        atom: PredicateAtom::Interactive,
                    }],
                    requires: vec![],
                    actions: vec![Action::SetEnv {
                        key: "A".into(),
                        value: EnvValue::String("1".into()),
                    }],
                },
                Block {
                    block_id: "non_interactive_b".into(),
                    when: vec![Predicate {
                        negated: true,
                        atom: PredicateAtom::Interactive,
                    }],
                    requires: vec![],
                    actions: vec![Action::SetEnv {
                        key: "B".into(),
                        value: EnvValue::String("1".into()),
                    }],
                },
            ],
        };

        let text = FishProvider.render(&ir);
        assert_eq!(text.matches("if not status is-interactive").count(), 1);
        assert!(text.contains("    # block: non_interactive_a\n    set -gx A \"1\";"));
        assert!(text.contains("    # block: non_interactive_b\n    set -gx B \"1\";"));
    }

    #[test]
    fn hoists_shared_interactive_and_login_guard_despite_order_difference() {
        let ir = ResolvedIr {
            blocks: vec![
                Block {
                    block_id: "a".into(),
                    when: vec![
                        Predicate {
                            negated: false,
                            atom: PredicateAtom::Interactive,
                        },
                        Predicate {
                            negated: false,
                            atom: PredicateAtom::Login,
                        },
                    ],
                    requires: vec![],
                    actions: vec![Action::SetEnv {
                        key: "A".into(),
                        value: EnvValue::String("1".into()),
                    }],
                },
                Block {
                    block_id: "b".into(),
                    when: vec![Predicate {
                        negated: false,
                        atom: PredicateAtom::Login,
                    }],
                    requires: vec![Predicate {
                        negated: false,
                        atom: PredicateAtom::Interactive,
                    }],
                    actions: vec![Action::SetEnv {
                        key: "B".into(),
                        value: EnvValue::String("1".into()),
                    }],
                },
            ],
        };

        let text = FishProvider.render(&ir);
        assert_eq!(
            text.matches("if begin; status is-interactive; and status is-login; end")
                .count(),
            1
        );
        assert!(text.contains("    # block: a\n    set -gx A \"1\";"));
        assert!(text.contains("    # block: b\n    set -gx B \"1\";"));
    }

    #[test]
    fn does_not_hoist_different_hoistable_combinations() {
        let ir = ResolvedIr {
            blocks: vec![
                Block {
                    block_id: "interactive_only".into(),
                    when: vec![Predicate {
                        negated: false,
                        atom: PredicateAtom::Interactive,
                    }],
                    requires: vec![],
                    actions: vec![Action::SetEnv {
                        key: "A".into(),
                        value: EnvValue::String("1".into()),
                    }],
                },
                Block {
                    block_id: "interactive_login".into(),
                    when: vec![
                        Predicate {
                            negated: false,
                            atom: PredicateAtom::Interactive,
                        },
                        Predicate {
                            negated: false,
                            atom: PredicateAtom::Login,
                        },
                    ],
                    requires: vec![],
                    actions: vec![Action::SetEnv {
                        key: "B".into(),
                        value: EnvValue::String("1".into()),
                    }],
                },
            ],
        };

        let text = FishProvider.render(&ir);
        assert_eq!(text.matches("if status is-interactive").count(), 1);
        assert_eq!(
            text.matches("if begin; status is-interactive; and status is-login; end")
                .count(),
            1
        );
    }

    #[test]
    fn renders_directory_predicates() {
        let ir = ResolvedIr {
            blocks: vec![Block {
                block_id: "cfg".into(),
                when: vec![],
                requires: vec![Predicate {
                    negated: false,
                    atom: PredicateAtom::Dir("~/.config/nvim".into()),
                }],
                actions: vec![Action::SetEnv {
                    key: "NVIM_CONFIGURED".into(),
                    value: EnvValue::String("1".into()),
                }],
            }],
        };

        let text = FishProvider.render(&ir);
        assert!(text.contains("if test -d \"$HOME/.config/nvim\""));
        assert!(text.contains("set -gx NVIM_CONFIGURED \"1\";"));
    }

    #[test]
    fn does_not_hoist_non_adjacent_blocks() {
        let ir = ResolvedIr {
            blocks: vec![
                Block {
                    block_id: "nvim".into(),
                    when: vec![Predicate {
                        negated: false,
                        atom: PredicateAtom::Interactive,
                    }],
                    requires: vec![],
                    actions: vec![Action::SetAlias {
                        name: "vim".into(),
                        value: "nvim".into(),
                    }],
                },
                Block {
                    block_id: "editor".into(),
                    when: vec![],
                    requires: vec![],
                    actions: vec![Action::SetEnv {
                        key: "EDITOR".into(),
                        value: EnvValue::String("nvim".into()),
                    }],
                },
                Block {
                    block_id: "bat".into(),
                    when: vec![Predicate {
                        negated: false,
                        atom: PredicateAtom::Interactive,
                    }],
                    requires: vec![],
                    actions: vec![Action::SetAlias {
                        name: "cat".into(),
                        value: "bat".into(),
                    }],
                },
            ],
        };

        let text = FishProvider.render(&ir);
        assert_eq!(text.matches("if status is-interactive").count(), 2);
    }
}
